name: "Convert TODOs to Issues"
on: ["push"]
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "Convert TODOs to Issues"
              uses: "alstr/todo-to-issue-action@v4"